export const projects = [
  // User 1 - 8 projects
  {
    idUser: 1,
    projectName: 'Project Alpha',
    description: 'A groundbreaking project focused on AI and machine learning.',
    githubLink: 'https://github.com/user/project-alpha',
    websiteLink: 'https://project-alpha.example.com',
    startDate: new Date('2022-01-15'),
    endDate: new Date('2022-06-30'),
  },
  {
    idUser: 1,
    projectName: 'Neural Vision',
    description: 'Computer vision tools powered by deep learning.',
    githubLink: 'https://github.com/user/neural-vision',
    websiteLink: 'https://neural-vision.example.com',
    startDate: new Date('2022-07-01'),
    endDate: new Date('2022-12-10'),
  },
  {
    idUser: 1,
    projectName: 'SmartChatbot',
    description: 'Conversational AI for customer support.',
    githubLink: 'https://github.com/user/smartchatbot',
    websiteLink: 'https://smartchatbot.example.com',
    startDate: new Date('2023-01-05'),
    endDate: new Date('2023-04-20'),
  },
  {
    idUser: 1,
    projectName: 'DataForge',
    description: 'ETL and data processing toolkit.',
    githubLink: 'https://github.com/user/dataforge',
    websiteLink: 'https://dataforge.example.com',
    startDate: new Date('2023-05-01'),
    endDate: new Date('2023-08-30'),
  },
  {
    idUser: 1,
    projectName: 'VisionAPI',
    description: 'API for image recognition and analysis.',
    githubLink: 'https://github.com/user/visionapi',
    websiteLink: 'https://visionapi.example.com',
    startDate: new Date('2023-09-10'),
    endDate: new Date('2024-01-15'),
  },
  {
    idUser: 1,
    projectName: 'ModelHub',
    description: 'Hub for deploying and managing ML models.',
    githubLink: 'https://github.com/user/modelhub',
    websiteLink: 'https://modelhub.example.com',
    startDate: new Date('2024-02-01'),
    endDate: new Date('2024-06-01'),
  },
  {
    idUser: 1,
    projectName: 'Predictify',
    description: 'Predictive analytics engine for business data.',
    githubLink: 'https://github.com/user/predictify',
    websiteLink: 'https://predictify.example.com',
    startDate: new Date('2024-06-10'),
    endDate: new Date('2024-10-20'),
  },
  {
    idUser: 1,
    projectName: 'AIBrain',
    description: 'AI-powered personal assistant.',
    githubLink: 'https://github.com/user/aibrain',
    websiteLink: 'https://aibrain.example.com',
    startDate: new Date('2024-11-01'),
    endDate: new Date('2025-03-15'),
  },

  // User 2 - 2 projects
  {
    idUser: 2,
    projectName: 'CryptoTracker',
    description: 'Real-time cryptocurrency market dashboard.',
    githubLink: 'https://github.com/user/cryptotracker',
    websiteLink: 'https://cryptotracker.example.com',
    startDate: new Date('2023-03-01'),
    endDate: new Date('2023-07-01'),
  },
  {
    idUser: 2,
    projectName: 'WalletGuard',
    description: 'Security suite for crypto wallets.',
    githubLink: 'https://github.com/user/walletguard',
    websiteLink: 'https://walletguard.example.com',
    startDate: new Date('2023-08-10'),
    endDate: new Date('2023-12-15'),
  },

  // User 3 - 4 projects
  {
    idUser: 3,
    projectName: 'EduPlatform',
    description: 'E-learning platform with interactive courses.',
    githubLink: 'https://github.com/user/eduplatform',
    websiteLink: 'https://eduplatform.example.com',
    startDate: new Date('2022-02-01'),
    endDate: new Date('2022-09-30'),
  },
  {
    idUser: 3,
    projectName: 'QuizMaster',
    description: 'Dynamic quiz generation tool.',
    githubLink: 'https://github.com/user/quizmaster',
    websiteLink: 'https://quizmaster.example.com',
    startDate: new Date('2022-10-10'),
    endDate: new Date('2023-01-31'),
  },
  {
    idUser: 3,
    projectName: 'StudyBuddy',
    description: 'AI-powered study assistant for students.',
    githubLink: 'https://github.com/user/studybuddy',
    websiteLink: 'https://studybuddy.example.com',
    startDate: new Date('2023-02-15'),
    endDate: new Date('2023-06-15'),
  },
  {
    idUser: 3,
    projectName: 'LearnTrack',
    description: 'Progress tracking for online learning.',
    githubLink: 'https://github.com/user/learntrack',
    websiteLink: 'https://learntrack.example.com',
    startDate: new Date('2023-07-01'),
    endDate: new Date('2023-11-30'),
  },
];
