export const projects = [
  {
    idUser: 1,
    projectName: 'Project Alpha',
    description: 'A groundbreaking project focused on AI development.',
    githubLink: 'https://github.com/uzytkownik/projekt',
    websiteLink: 'https://project-alpha.com',
  },
  {
    idUser: 1,
    projectName: 'Beta Builder',
    description: 'A powerful tool for building modular frontend components.',
    githubLink: 'https://github.com/uzytkownik/beta-builder',
    websiteLink: 'https://beta-builder.dev',
  },
  {
    idUser: 1,
    projectName: 'Gamma Analytics',
    description: 'An analytics dashboard powered by machine learning.',
    githubLink: 'https://github.com/uzytkownik/gamma-analytics',
    websiteLink: 'https://gamma-analytics.io',
  },
  {
    idUser: 1,
    projectName: 'Delta Docs',
    description: 'A sleek documentation generator for modern APIs.',
    githubLink: 'https://github.com/uzytkownik/delta-docs',
    websiteLink: 'https://deltadocs.org',
  },
  {
    idUser: 1,
    projectName: 'Epsilon Engine',
    description: 'A real-time game engine for web-based 3D experiences.',
    githubLink: 'https://github.com/uzytkownik/epsilon-engine',
    websiteLink: 'https://epsilonengine.com',
  },
  {
    idUser: 1,
    projectName: 'Zeta Zoom',
    description: 'A high-performance image compression and zoom tool.',
    githubLink: 'https://github.com/uzytkownik/zeta-zoom',
    websiteLink: 'https://zetazoom.io',
  },
  {
    idUser: 1,
    projectName: 'Eta Emailer',
    description: 'A customizable email automation platform for startups.',
    githubLink: 'https://github.com/uzytkownik/eta-emailer',
    websiteLink: 'https://etaemailer.com',
  },
  {
    idUser: 2,
    projectName: 'Theta Tasker',
    description: 'An intuitive task management app for distributed teams.',
    githubLink: 'https://github.com/uzytkownik/theta-tasker',
    websiteLink: 'https://thetatasker.app',
  },
  {
    idUser: 2,
    projectName: 'Iota Insights',
    description: 'Business intelligence and insights from data streams.',
    githubLink: 'https://github.com/uzytkownik/iota-insights',
    websiteLink: 'https://iotainsights.io',
  },
  {
    idUser: 2,
    projectName: 'Kappa Keeper',
    description: 'A secure digital vault for storing encrypted credentials.',
    githubLink: 'https://github.com/uzytkownik/kappa-keeper',
    websiteLink: 'https://kappakeeper.com',
  },
];
