export const users = [
  {
    linkedinId: '100000001',
    firstName: 'Alice',
    lastName: 'Smith',
    email: 'alice.smith@example.com',
    description: 'Frontend developer with a passion for design.',
    job: 'Frontend Developer',
    gitUrl: 'https://github.com/alicesmith',
    linkedinUrl: 'https://linkedin.com/in/alicesmith',
    locationId: 1,
  },
  {
    linkedinId: '100000002',
    firstName: 'Bob',
    lastName: 'Johnson',
    email: 'bob.johnson@example.com',
    description: 'Backend guru and database expert.',
    job: 'Backend Developer',
    gitUrl: 'https://github.com/bobjohnson',
    linkedinUrl: 'https://linkedin.com/in/bobjohnson',
    locationId: 1,
  },
  {
    linkedinId: '100000003',
    firstName: 'Charlie',
    lastName: 'Brown',
    email: 'charlie.brown@example.com',
    description: 'Fullstack developer who loves TypeScript.',
    job: 'Fullstack Developer',
    gitUrl: 'https://github.com/charliebrown',
    linkedinUrl: 'https://linkedin.com/in/charliebrown',
    locationId: 1,
  },
  {
    linkedinId: '100000004',
    firstName: 'Diana',
    lastName: 'Evans',
    email: 'diana.evans@example.com',
    description: 'Cloud enthusiast and DevOps engineer.',
    job: 'DevOps Engineer',
    gitUrl: 'https://github.com/dianaevans',
    linkedinUrl: 'https://linkedin.com/in/dianaevans',
    locationId: 1,
  },
  {
    linkedinId: '100000005',
    firstName: 'Ethan',
    lastName: 'Wright',
    email: 'ethan.wright@example.com',
    description: 'Mobile app developer focusing on Flutter.',
    job: 'Mobile Developer',
    gitUrl: 'https://github.com/ethanwright',
    linkedinUrl: 'https://linkedin.com/in/ethanwright',
    locationId: 1,
  },
  {
    linkedinId: '100000006',
    firstName: 'Fiona',
    lastName: 'Green',
    email: 'fiona.green@example.com',
    description: 'QA engineer who ensures software quality.',
    job: 'QA Engineer',
    gitUrl: 'https://github.com/fionagreen',
    linkedinUrl: 'https://linkedin.com/in/fionagreen',
    locationId: 1,
  },
  {
    linkedinId: '100000007',
    firstName: 'George',
    lastName: 'Hill',
    email: 'george.hill@example.com',
    description: 'Game developer with Unity experience.',
    job: 'Game Developer',
    gitUrl: 'https://github.com/georgehill',
    linkedinUrl: 'https://linkedin.com/in/georgehill',
    locationId: 1,
  },
  {
    linkedinId: '100000008',
    firstName: 'Hannah',
    lastName: 'Scott',
    email: 'hannah.scott@example.com',
    description: 'AI/ML researcher and data scientist.',
    job: 'Data Scientist',
    gitUrl: 'https://github.com/hannahscott',
    linkedinUrl: 'https://linkedin.com/in/hannahscott',
    locationId: 1,
  },
  {
    linkedinId: '100000009',
    firstName: 'Ian',
    lastName: 'Turner',
    email: 'ian.turner@example.com',
    description: 'Cybersecurity expert with a focus on app security.',
    job: 'Security Engineer',
    gitUrl: 'https://github.com/ianturner',
    linkedinUrl: 'https://linkedin.com/in/ianturner',
    locationId: 1,
  },
  {
    linkedinId: '100000010',
    firstName: 'Julia',
    lastName: 'Morris',
    email: 'julia.morris@example.com',
    description: 'Tech lead and agile coach.',
    job: 'Tech Lead',
    gitUrl: 'https://github.com/juliamorris',
    linkedinUrl: 'https://linkedin.com/in/juliamorris',
    locationId: 1,
  },
  {
    linkedinId: '100000011',
    firstName: 'Kevin',
    lastName: 'Baker',
    email: 'kevin.baker@example.com',
    description: 'Cloud architect and automation pro.',
    job: 'Cloud Architect',
    gitUrl: 'https://github.com/kevinbaker',
    linkedinUrl: 'https://linkedin.com/in/kevinbaker',
    locationId: 2,
  },
  {
    linkedinId: '100000012',
    firstName: 'Laura',
    lastName: 'Carter',
    email: 'laura.carter@example.com',
    description: 'UX/UI designer with a user-first mindset.',
    job: 'UX Designer',
    gitUrl: 'https://github.com/lauracarter',
    linkedinUrl: 'https://linkedin.com/in/lauracarter',
    locationId: 2,
  },
  {
    linkedinId: '100000013',
    firstName: 'Michael',
    lastName: 'King',
    email: 'michael.king@example.com',
    description: 'Blockchain developer and smart contract specialist.',
    job: 'Blockchain Developer',
    gitUrl: 'https://github.com/michaelking',
    linkedinUrl: 'https://linkedin.com/in/michaelking',
    locationId: 4,
  },
  {
    linkedinId: '100000014',
    firstName: 'Natalie',
    lastName: 'Reed',
    email: 'natalie.reed@example.com',
    description: 'Embedded systems and IoT engineer.',
    job: 'Embedded Engineer',
    gitUrl: 'https://github.com/nataliereed',
    linkedinUrl: 'https://linkedin.com/in/nataliereed',
    locationId: 5,
  },
  {
    linkedinId: '100000015',
    firstName: 'Oscar',
    lastName: 'Collins',
    email: 'oscar.collins@example.com',
    description: 'AR/VR enthusiast working with Unity and Unreal.',
    job: 'AR/VR Developer',
    gitUrl: 'https://github.com/oscarcollins',
    linkedinUrl: 'https://linkedin.com/in/oscarcollins',
    locationId: 6,
  },
  {
    linkedinId: '100000016',
    firstName: 'Paula',
    lastName: 'Brooks',
    email: 'paula.brooks@example.com',
    description: 'Scrum Master with a knack for team coordination.',
    job: 'Scrum Master',
    gitUrl: 'https://github.com/paulabrooks',
    linkedinUrl: 'https://linkedin.com/in/paulabrooks',
    locationId: 7,
  },
  {
    linkedinId: '100000017',
    firstName: 'Quentin',
    lastName: 'Young',
    email: 'quentin.young@example.com',
    description: 'DevRel engineer and technical writer.',
    job: 'Developer Advocate',
    gitUrl: 'https://github.com/quentinyoung',
    linkedinUrl: 'https://linkedin.com/in/quentinyoung',
    locationId: 9,
  },
  {
    linkedinId: '100000018',
    firstName: 'Rachel',
    lastName: 'Morgan',
    email: 'rachel.morgan@example.com',
    description: 'Robotics engineer building smart machines.',
    job: 'Robotics Engineer',
    gitUrl: 'https://github.com/rachelmorgan',
    linkedinUrl: 'https://linkedin.com/in/rachelmorgan',
    locationId: 11,
  },
  {
    linkedinId: '100000019',
    firstName: 'Steve',
    lastName: 'Adams',
    email: 'steve.adams@example.com',
    description: 'Site reliability engineer focused on uptime.',
    job: 'SRE',
    gitUrl: 'https://github.com/steveadams',
    linkedinUrl: 'https://linkedin.com/in/steveadams',
    locationId: 13,
  },
  {
    linkedinId: '100000020',
    firstName: 'Tina',
    lastName: 'Ross',
    email: 'tina.ross@example.com',
    description: 'Big data engineer working with Spark and Hadoop.',
    job: 'Big Data Engineer',
    gitUrl: 'https://github.com/tinaross',
    linkedinUrl: 'https://linkedin.com/in/tinaross',
    locationId: 14,
  },
];
