export const users = [
  {
    linkedinId: '100000001',
    firstName: 'Alice',
    lastName: 'Smith',
    email: 'alice.smith@example.com',
    description: 'Frontend developer with a passion for design.',
    job: 'Frontend Developer',
    gitUrl: 'https://github.com/alicesmith',
    linkedinUrl: 'https://linkedin.com/in/alicesmith',
  },
  {
    linkedinId: '100000002',
    firstName: 'Bob',
    lastName: 'Johnson',
    email: 'bob.johnson@example.com',
    description: 'Backend guru and database expert.',
    job: 'Backend Developer',
    gitUrl: 'https://github.com/bobjohnson',
    linkedinUrl: 'https://linkedin.com/in/bobjohnson',
  },
  {
    linkedinId: '100000003',
    firstName: 'Charlie',
    lastName: 'Brown',
    email: 'charlie.brown@example.com',
    description: 'Fullstack developer who loves TypeScript.',
    job: 'Fullstack Developer',
    gitUrl: 'https://github.com/charliebrown',
    linkedinUrl: 'https://linkedin.com/in/charliebrown',
  },
  {
    linkedinId: '100000004',
    firstName: 'Diana',
    lastName: 'Evans',
    email: 'diana.evans@example.com',
    description: 'Cloud enthusiast and DevOps engineer.',
    job: 'DevOps Engineer',
    gitUrl: 'https://github.com/dianaevans',
    linkedinUrl: 'https://linkedin.com/in/dianaevans',
  },
  {
    linkedinId: '100000005',
    firstName: 'Ethan',
    lastName: 'Wright',
    email: 'ethan.wright@example.com',
    description: 'Mobile app developer focusing on Flutter.',
    job: 'Mobile Developer',
    gitUrl: 'https://github.com/ethanwright',
    linkedinUrl: 'https://linkedin.com/in/ethanwright',
  },
  {
    linkedinId: '100000006',
    firstName: 'Fiona',
    lastName: 'Green',
    email: 'fiona.green@example.com',
    description: 'QA engineer who ensures software quality.',
    job: 'QA Engineer',
    gitUrl: 'https://github.com/fionagreen',
    linkedinUrl: 'https://linkedin.com/in/fionagreen',
  },
  {
    linkedinId: '100000007',
    firstName: 'George',
    lastName: 'Hill',
    email: 'george.hill@example.com',
    description: 'Game developer with Unity experience.',
    job: 'Game Developer',
    gitUrl: 'https://github.com/georgehill',
    linkedinUrl: 'https://linkedin.com/in/georgehill',
  },
  {
    linkedinId: '100000008',
    firstName: 'Hannah',
    lastName: 'Scott',
    email: 'hannah.scott@example.com',
    description: 'AI/ML researcher and data scientist.',
    job: 'Data Scientist',
    gitUrl: 'https://github.com/hannahscott',
    linkedinUrl: 'https://linkedin.com/in/hannahscott',
  },
  {
    linkedinId: '100000009',
    firstName: 'Ian',
    lastName: 'Turner',
    email: 'ian.turner@example.com',
    description: 'Cybersecurity expert with a focus on app security.',
    job: 'Security Engineer',
    gitUrl: 'https://github.com/ianturner',
    linkedinUrl: 'https://linkedin.com/in/ianturner',
  },
  {
    linkedinId: '100000010',
    firstName: 'Julia',
    lastName: 'Morris',
    email: 'julia.morris@example.com',
    description: 'Tech lead and agile coach.',
    job: 'Tech Lead',
    gitUrl: 'https://github.com/juliamorris',
    linkedinUrl: 'https://linkedin.com/in/juliamorris',
  },
];
